### ISSUE TITLE
希望作者支持“层级”结构，

### ISSUE THREAD

**Issue by aidreampai** [struy-cn/Y-TOC#1]
希望作者支持“层级”结构，

1. xxx
    1.1 xxxx

**Comment by StruggleYang** [comment]
> 希望作者支持 “层级” 结构，
> 
> 1. xxx
>    1.1 xxxx

现在你可以双击带编号的项将其提高为上层章节，或者双击变回来：
使用预览：

![iShot_2024-03-24_13 07 03](https://github.com/struy-cn/Y-TOC/assets/20719880/26198877-34d3-472f-b595-8329e5ee2961)

效果：
![《史蒂夫乔布斯传》 (1)](https://github.com/struy-cn/Y-TOC/assets/20719880/b7f9fe71-a0bb-419e-b01d-54a2fe31bdf4)
